### ISSUE TITLE
Add new mode to support AI play with Human

### ISSUE THREAD

**Issue by htomtom** [ozzi7/TicTacToe-DL-RL#2]
This is a good project. When a new weight is genertated, how can  we run the program to support AI vs human player? If the new mode is added to the main() with arguments such as " tictactoe.exe -mode human ", then we can manually input the move such as the coordinates "3,4" etc.  Then we can test the AI strength with console UI, and the program will be more interactive.

**Comment by ozzi7** [comment]
Hello @htomtom, thank you for your comments. The idea was to port this to C++ first, C# was more convenient to test things. But you can play vs. AI if you put the weights.txt file in the Training folder and run the executable with TicTacToe-DL-RL.exe play weights.txt. There are still a lot of TODOs regarding this feature but nevertheless I will close this issue for now. Feel free to open a new one if you need something specific.
